default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  port: 5432
  username: postgres
  password: postgres
  host: localhost
 
development:
  <<: *default
  database: rails_google_development


test:
  <<: *default
  database: trails_google_test

production:
  <<: *default
  database: rails_google_production

